baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "anatole"

[params]
title = "I'm fadhil"
author = "Fadhil"
description = "www.gunadarma.ac.id"
profilePicture = "/me-min.jpg"