baseURL = "http://example.org/"
languageCode = "en-us"
theme = "anatole"
title = "My New Hugo Site"
[params]
author = "Fadhil"
description = "www.gunadarma.ac.id"
profilePicture = "/me-min.jpg"
title = "I'm fadhil"
